name: wf-cd-develop
on:
  push:
    branches:
      - develop
jobs:
  deploy-on-render:
    runs-on: ubuntu-latest
    environment:
      name: "development"
      url: https://taskflow-latest-ojkj.onrender.com/
    steps:
      - name: Welcome Step
        run: echo "Deploying On Render"
      - name: Deploying On Render
        run: curl -X POST ${{secrets.DEPLOY_HOOK_RENDER_URL}}
      - name: Deployment Success 
        run: echo "Successfully Deployed App On Render"